version: '3'
services:
    app:
        image: node:16
        working_dir: /home/node/app
        command: npm run dev
        volumes:
            - .:/home/node/app
        ports:
            - 3000:3000
        networks:
            - app
        restart: on-failure
networks:
    app:
        driver: bridge